'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

var FinancefilterSchema = new Schema({
  center: String,
  centerShort: String,
  functionName: String,
  activity: String,
  spent: String,
  urg: String,
  original: Number,
  modified1: Number,
  modified2: Number,
  modified3: Number,
  modified4: Number,
  modified5: Number,
  modified6: Number,
  modified7: Number,
  modified8: Number,
  modified9: Number,
  modified10: Number,
  modified11: Number,
  modified12: Number,
  modifiedTo2: Number,
  modifiedTo3: Number,
  modifiedTo4: Number,
  modifiedTo5: Number,
  modifiedTo6: Number,
  modifiedTo7: Number,
  modifiedTo8: Number,
  modifiedTo9: Number,
  modifiedTo10: Number,
  modifiedTo11: Number,
  modifiedTo12: Number,
  executed1: Number,
  executed2: Number,
  executed3: Number,
  executed4: Number,
  executed5: Number,
  executed6: Number,
  executed7: Number,
  executed8: Number,
  executed9: Number,
  executed10: Number,
  executed11: Number,
  executed12: Number,
  executedTo2: Number,
  executedTo3: Number,
  executedTo4: Number,
  executedTo5: Number,
  executedTo6: Number,
  executedTo7: Number,
  executedTo8: Number,
  executedTo9: Number,
  executedTo10: Number,
  executedTo11: Number,
  executedTo12: Number
});

module.exports = mongoose.model('Financefilter', FinancefilterSchema);
